version: 1
services:
  - type: web
    name: casting-agency
    env: python
    buildCommand: |
      echo "Running setup.sh..."
      bash setup.sh  # Runs your setup script
      echo "Running migrations..."
      flask db upgrade  # Run migrations after setup
      echo "Migrations completed"
    startCommand: gunicorn app:app
